_BASE_: "../../../detectron2/configs/COCO-PanopticSegmentation/Base-Panoptic-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-PanopticSegmentation/panoptic_fpn_R_50_3x/139514569/model_final_c10459.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
