name: detectron2-pipeline
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.6.5
  - pip
  - numpy==1.17.2
  - tqdm=4.37.0
  - pytest==5.1.1
  - pytorch==1.3.1
  - torchvision==0.4.2
  - cython=0.29.14
  - munkres=1.0.12
  - pillow=6.2.1
  - pip:
    - opencv-contrib-python==4.0.0.21
    - git+https://github.com/facebookresearch/fvcore@4354c8c09e5dfb22f6e84172d46b7ece24446bc1
    - git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
